### ISSUE TITLE
feat: automatic release

### ISSUE THREAD

**Issue by Fersoil** [mini-pw/PvSTATEM#169]
### Feature Description

We want to add automatic releases and tagging. The tags should be created if there is a commit with increased package version in the DESCRIPTION file.

The sync between NEWS.md and release notes are not necessary

### Use Case

To track better the versioning, the relases should be created

### Additional Context

Additionally, we could add automatic CRAN release, the instructions are described here:
https://github.com/ThinkR-open/prepare-for-cran

**Comment by ZetrextJG** [comment]
Closing the issue

**Comment by Fersoil** [comment]
imho this is not completed yet, but we could decide if this feature should be implemented
