### ISSUE TITLE
feat: Options for extrapolation

### ISSUE THREAD

**Issue by Fersoil** [mini-pw/PvSTATEM#170]
### Feature Description

There should be some options for prediction with specific extrapolation techniques, such as:
- limited extrapolation
- thresholding the value

This options probably are relevant to the upper limit only

### Use Case

In general the `predict` method from the `Model` instance should provide this kind of choice, which should be also transferred to the `process_plate` function as well

**Comment by ZetrextJG** [comment]
I think that the addition of `over_max_extrapolation` solves that issue
