### ISSUE TITLE
bug: fix reading intelliflex files

### ISSUE THREAD

**Issue by Fersoil** [mini-pw/PvSTATEM#21]
Our package seems to be struggling with the intelliflex files, this should be fixed

**Comment by ZetrextJG** [comment]
Could you provide a sample of a intelliflex file

**Comment by Fersoil** [comment]
all our datasets are in the shared folder on onedrive, intelliflex is in the private datasets

**Comment by ZetrextJG** [comment]
New parser will be able to parse Intelliflex format file
