### ISSUE TITLE
feat: model carrying more info

### ISSUE THREAD

**Issue by Fersoil** [mini-pw/PvSTATEM#86]
I would suggest that a `Model` instance could have the analyte name embedded in its structure.

As a result we could skip adding repetitive arguments in the `plot_standard_curve_analyte_with_model`:
Instead of 
```plot_standard_curve_analyte_with_model(plate, model, analyte_name="Spike_6P")```
we could simply use
```plot_standard_curve_analyte_with_model(plate, mode)```

What is more, for now, it is possible to predict dilution for different analyte than the model was originally fitted for:
```
model <- create_standard_curve_model_analyte(plate, analyte_name = "OC43_S")


plot_standard_curve_analyte_with_model(plate, analyte_name = "OC43_S", model)
plot_standard_curve_analyte_with_model(plate, analyte_name = "Spike_6P", model)
```

**Comment by ZetrextJG** [comment]
I think that is a good idea. Feel free to implement that anytime you want
