### ISSUE TITLE
bug: hande label stacking on each other in mfi distribution plot 

### ISSUE THREAD

**Issue by nizwant** [mini-pw/PvSTATEM#96]
<img width="101" alt="image" src="https://github.com/user-attachments/assets/c5fd3e2f-0c2b-432d-ada3-c774c2a53ddf">

**Comment by ZetrextJG** [comment]
The best I could think of is alternating the labels and changing the color to different one.
![image](https://github.com/user-attachments/assets/e809c928-8112-4c89-b959-445476a0abe8)

The implementation is here : # (built opon the #103 PR)
