### ISSUE TITLE
bug: fix ranges of x axis for the standard curve plot with model

### ISSUE THREAD

**Issue by Fersoil** [mini-pw/PvSTATEM#99]

**Comment by Fersoil** [comment]
can't reproduce this error, the plot looks good 
![image](https://github.com/user-attachments/assets/bb494591-8556-489a-a8a5-bd287b83c172)

@ZetrextJG could you try reproducing it?

**Comment by ZetrextJG** [comment]
The negative values introduced by the blank adjustment seems to be the issue. Re-implementation of the blank adjustment: #102
